version: '3.8'

services:
    php-fpm:
        build: .docker/php
        container_name: workshop-php
        entrypoint: .docker/entrypoint.sh
        environment:
        - COMPOSER_MEMORY_LIMIT=2G
        - ENVIRONMENT=local
        volumes:
        - .:/var/www
        networks:
        - workshop-network
        user: "1000:www-data"
    nginx:
        build: .docker/nginx
        container_name: workshop-nginx
        restart: always
        tty: true
        ports:
        - 3335:80
        volumes:
        - .:/var/www
        networks:
        - workshop-network
        depends_on:
        - php-fpm

networks:
  workshop-network:
    driver: bridge
